name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Create virtualenv
        run: python -m venv .venv

      - name: Install dependencies
        run: . .venv/bin/activate && make init

      - name: Run checks
        run: . .venv/bin/activate && make check

      - name: Run coverage
        run: |
          . .venv/bin/activate
          coverage run -m pytest --maxfail=1 --disable-warnings
          coverage xml
          coverage report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
